title: Devugger
url: "https://www.mariodmpereira.com"
author:
  name: "Mário Pereira"
  username: "mariodmpereira"
  vimeo: "https://vimeo.com/mariodmpereira/"
  linkedin: "https://www.linkedin.com/in/mariodmpereira/"
  github: "https://github.com/mariodmpereira/"
remote_theme: just-the-docs/just-the-docs
color_scheme: dark
plugins:
  - jekyll-feed

aux_links:
  "Home":
    - "//mariodmpereira.com/"
  "Blog":
    - "//mariodmpereira.com/blog/"
  "GitHub":
    - "//github.com/mariodmpereira/"
  "Linkedin":
    - "//linkedin.com/in/mariodmpereira/"